/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArticlesIndexRouteImport } from './routes/articles/index'
import { Route as ArticlesSlugRouteImport } from './routes/articles/$slug'
import { Route as BooksIndexRouteImport } from './routes/books/index'
import { Route as BooksSlugRouteImport } from './routes/books/$slug'
import { Route as LinksIndexRouteImport } from './routes/links/index'
import { Route as NowIndexRouteImport } from './routes/now/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksIndexRoute = BooksIndexRouteImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksSlugRoute = BooksSlugRouteImport.update({
  id: '/books/$slug',
  path: '/books/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LinksIndexRoute = LinksIndexRouteImport.update({
  id: '/links/',
  path: '/links/',
  getParentRoute: () => rootRouteImport,
} as any)
const NowIndexRoute = NowIndexRouteImport.update({
  id: '/now/',
  path: '/now/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/books/$slug': typeof BooksSlugRoute
  '/articles/': typeof ArticlesIndexRoute
  '/books/': typeof BooksIndexRoute
  '/links/': typeof LinksIndexRoute
  '/now/': typeof NowIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/books/$slug': typeof BooksSlugRoute
  '/articles': typeof ArticlesIndexRoute
  '/books': typeof BooksIndexRoute
  '/links': typeof LinksIndexRoute
  '/now': typeof NowIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/books/$slug': typeof BooksSlugRoute
  '/articles/': typeof ArticlesIndexRoute
  '/books/': typeof BooksIndexRoute
  '/links/': typeof LinksIndexRoute
  '/now/': typeof NowIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/articles/$slug'
    | '/books/$slug'
    | '/articles/'
    | '/books/'
    | '/links/'
    | '/now/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/articles/$slug'
    | '/books/$slug'
    | '/articles'
    | '/books'
    | '/links'
    | '/now'
  id:
    | '__root__'
    | '/'
    | '/articles/$slug'
    | '/books/$slug'
    | '/articles/'
    | '/books/'
    | '/links/'
    | '/now/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  BooksSlugRoute: typeof BooksSlugRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
  BooksIndexRoute: typeof BooksIndexRoute
  LinksIndexRoute: typeof LinksIndexRoute
  NowIndexRoute: typeof NowIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/': {
      id: '/books/'
      path: '/books'
      fullPath: '/books/'
      preLoaderRoute: typeof BooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$slug': {
      id: '/books/$slug'
      path: '/books/$slug'
      fullPath: '/books/$slug'
      preLoaderRoute: typeof BooksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links/': {
      id: '/links/'
      path: '/links'
      fullPath: '/links/'
      preLoaderRoute: typeof LinksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/now/': {
      id: '/now/'
      path: '/now'
      fullPath: '/now/'
      preLoaderRoute: typeof NowIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArticlesSlugRoute: ArticlesSlugRoute,
  BooksSlugRoute: BooksSlugRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
  BooksIndexRoute: BooksIndexRoute,
  LinksIndexRoute: LinksIndexRoute,
  NowIndexRoute: NowIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
